### PR TITLE
fix for Unparseable date format

### LINKED ISSUE #309: Unparseable dateformat usinf Xdrip+ in follower mode with nightscout.
img_20180217_140511
Using xdrip not on uploader phone but in follow mode, I can't sync from Nightscout due to parse errors on date format. 

Is there something I can change in the uploaded phone to become 'dateformat-compliant'?

### PR DESCRIPTION
**Pull request by tolot27**
Change ISO 8601 date string parsing to be able to read Nightscout data if DE_NORMALIZE_DATES is enabled.

A unit test is implemented as well. Test strings and their correction can be seen at https://regex101.com/r/utF21U.

A detailed description is added to the individual commits, especially to 5a30fc2. The unit test is designed to cover also the Android SDK condition check.

Fixes #309, #1062

### CODE REVIEW

**Comment by jamorham** [comment]
I think you need to merge the google truth update to the gradle build to resolve the conflicts on this

File: app/src/main/java/com/eveningoutpost/dexdrip/Models/DateUtil.java [hunk 1]
```diff
@@ -1,81 +1,44 @@
...
-        }
-    }
-
-    public static Date tolerantFromISODateString(String isoDateString)
-            throws Exception {
-        try {
-            return fromISODateString(isoDateString.replaceFirst("\\.[0-9][0-9][0-9]Z$", "Z"));
-        } catch (java.text.ParseException e) {
-            return fromISODateString2(isoDateString);
+    public static Date tolerantFromISODateString(String isoDateString) {
```
Comment (jamorham) [inline app/src/main/java/com/eveningoutpost/dexdrip/Models/DateUtil.java:35]: I haven't examined this in any detail but I'm kind of nervous about modifying this code. Are you confident the new unit tests cover whatever might have been seen and be accepted by this method?

Comment (tolot27) [reply app/src/main/java/com/eveningoutpost/dexdrip/Models/DateUtil.java:35]: I've added an additional test case to cover date/time strings without seconds but offset value (FORMAT_DATE_ISO3). Now all former string formats are covered and the regex fixes much more "wrong" date/time strings. See https://regex101.com/r/utF21U/1 for a clean impression.

**Review by jamorham — APPROVED** [review]
